// Generated by reverse-engineering tool

import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { Report } from './report.entity';

@Entity('report_parameter')
export class ReportParameter {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ name: 'report_id', type: 'int' })
  reportId?: number | null;

  @Column({ name: 'parameter_name', length: 255 })
  parameterName?: string | null;

  @Column({ length: 255 })
  label?: string | null;

  @Column({ name: 'data_type', length: 100 })
  dataType?: string | null;

  @Column({ name: 'created_at', type: 'timestamp', default: () => "CURRENT_TIMESTAMP" })
  createdAt?: Date | null;

  @Column({ name: 'updated_at', type: 'timestamp', default: () => "CURRENT_TIMESTAMP" })
  updatedAt?: Date | null;

  @Column({ name: 'deleted_at', type: 'timestamp' })
  deletedAt?: Date | null;

  @Column({ name: 'created_by', length: 255 })
  createdBy?: string | null;

  @Column({ name: 'updated_by', length: 255 })
  updatedBy?: string | null;

  @Column({ name: 'deleted_by', length: 255 })
  deletedBy?: string | null;

  @Column({ name: 'query_parameter', length: 255 })
  queryParameter?: string | null;

  @Column({ name: 'input_field_type', length: 100 })
  inputFieldType?: string | null;

  @Column({ name: 'option_type', length: 100 })
  optionType?: string | null;

  @Column({ type: 'jsonb' })
  option?: any | null;

  @Column({ name: 'order_no', type: 'int' })
  orderNo?: number | null;

  @ManyToOne(() => Report)
  @JoinColumn({ name: 'report_id' })
  report?: Report;

}