// Generated by reverse-engineering tool

import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { Customers } from './customers.entity';

@Entity('sales')
export class Sales {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ name: 'customer_id', type: 'int' })
  customerId?: number | null;

  @Column({ length: 100 })
  region?: string | null;

  @Column({ type: 'decimal', precision: 10, scale: 2 })
  amount?: number | null;

  @Column({ type: 'date', default: 'CURRENT_DATE' })
  date?: Date | null;

  @ManyToOne(() => Customers)
  @JoinColumn({ name: 'customer_id' })
  customers?: Customers;

}