// Generated by reverse-engineering tool

import { Column, Entity, PrimaryColumn } from 'typeorm';

@Entity('users')
export class Users {
  @PrimaryColumn()
  id: string;

  @Column({ length: 255, nullable: false })
  name: string;

  @Column({ length: 255, nullable: false })
  email: string;

  @Column({ length: 255, nullable: false })
  password: string;

  @Column({ name: 'mobile_no', length: 255 })
  mobileNo?: string | null;

  @Column({ name: 'profile_image', length: 255 })
  profileImage?: string | null;

  @Column({ length: 255 })
  country?: string | null;

  @Column({ length: 255 })
  city?: string | null;

  @Column({ length: 255, nullable: false })
  role: string;

  @Column({ name: 'createdAt', type: 'timestamptz', nullable: false, default: () => "CURRENT_TIMESTAMP" })
  createdat: Date;

  @Column({ name: 'updatedAt', type: 'timestamptz', nullable: false, default: () => "CURRENT_TIMESTAMP" })
  updatedat: Date;

}